version: '3.7'

services: 
  backend:
    container_name: 'api-node-leads2b'
    image: matheuspaz/node:13.11.0-alpine
    ports: 
      - 3000:3000
    volumes: 
     - ./api:/app
    working_dir: /app
    command: 'yarn development'

  mongo:
    image: mongo
    container_name: 'mongodb-leads2b'
    restart: always
    volumes: 
      - ./.data/db:/data/db
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: leads2b
      MONGO_INITDB_ROOT_PASSWORD: leads2b